[package]
name = "lean-homotopy-theory"
version = "0.1"
lean_version = "3.4.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "89431cf4f01ff0f6b4005f96795a23571258cbf0"}
